-- Default catalog by trade (611 items, imported from the industry-standard CSV)
-- + catalog versioning so masters can pull NEWER defaults without losing edits.
--
-- Decisions: all items are WORK (the CSV is a labour reference, no material column);
-- prices = orientative market hint where the CSV had one (256), else 0 (the
-- master sets their own) — so the price CHECK is relaxed from > 0 to >= 0.

-- 1. New trades (PAINTER/DRYWALL/FLOORING/DEMOLITION) and units (POINT/PERCENT).
ALTER TABLE user_trades       DROP CONSTRAINT user_trades_trade_check;
ALTER TABLE user_trades       ADD  CONSTRAINT user_trades_trade_check
    CHECK (trade IN ('ELECTRICAL', 'PLUMBING', 'TILING', 'BUILDER', 'PAINTER', 'DRYWALL', 'FLOORING', 'DEMOLITION', 'GENERAL', 'OTHER'));

ALTER TABLE catalog_templates DROP CONSTRAINT catalog_templates_trade_check;
ALTER TABLE catalog_templates ADD  CONSTRAINT catalog_templates_trade_check
    CHECK (trade IN ('ELECTRICAL', 'PLUMBING', 'TILING', 'BUILDER', 'PAINTER', 'DRYWALL', 'FLOORING', 'DEMOLITION', 'GENERAL', 'OTHER'));

ALTER TABLE catalog_items     DROP CONSTRAINT catalog_items_unit_check;
ALTER TABLE catalog_items     ADD  CONSTRAINT catalog_items_unit_check
    CHECK (unit IN ('M2', 'M', 'LINEAR_METER', 'PIECE', 'KG', 'HOUR', 'SET', 'M3', 'T', 'POINT', 'PERCENT'));

ALTER TABLE estimate_items    DROP CONSTRAINT estimate_items_unit_check;
ALTER TABLE estimate_items    ADD  CONSTRAINT estimate_items_unit_check
    CHECK (unit IN ('M2', 'M', 'LINEAR_METER', 'PIECE', 'KG', 'HOUR', 'SET', 'M3', 'T', 'POINT', 'PERCENT'));

ALTER TABLE catalog_templates DROP CONSTRAINT catalog_templates_unit_check;
ALTER TABLE catalog_templates ADD  CONSTRAINT catalog_templates_unit_check
    CHECK (unit IN ('M2', 'M', 'LINEAR_METER', 'PIECE', 'KG', 'HOUR', 'SET', 'M3', 'T', 'POINT', 'PERCENT'));

-- 2. Allow a 0 (empty) price — the master fills it in.
ALTER TABLE catalog_templates DROP CONSTRAINT catalog_templates_price_check;
ALTER TABLE catalog_templates ADD  CONSTRAINT catalog_templates_price_check
    CHECK (suggested_price >= 0);

ALTER TABLE catalog_items     DROP CONSTRAINT catalog_items_price_check;
ALTER TABLE catalog_items     ADD  CONSTRAINT catalog_items_price_check
    CHECK (default_price >= 0);

-- 3. Versioning columns. added_in_version = the catalog version a template first
--    appeared in (all current = 1). last_synced_catalog_version = the version a
--    master last pulled from (so "Add new from catalog" only offers newer items).
ALTER TABLE catalog_templates ADD COLUMN added_in_version INT NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN last_synced_catalog_version INT NOT NULL DEFAULT 0;

-- 4. Replace the starter templates with the full by-trade default set. Templates
--    are global read-only reference data (CatalogItem copies VALUES, not FKs), so
--    a delete + re-insert never touches any user's own catalog_items.
DELETE FROM catalog_templates;

INSERT INTO catalog_templates (id, trade, category, name, type, unit, suggested_price, added_in_version) VALUES
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Планування ділянки і нівелювання', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Перенесення землі (не далі 20м)', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Копання траншей ям котловану вручну', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Планування грунту до 10 см', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Копка траншей глибиною 0.5м шириною 35см', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Зворотня засипка траншеї', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Піщана подушка з ущільненням', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Щебенева підготовка до 10 см', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Монтаж та демонтаж опалубки для фундаменту', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Облаштування фундаменту (приймання бетону арматура)', 'WORK', 'M3', 4000.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Приготування бетонного розчину для фундаменту', 'WORK', 'M3', 1800.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Бетонування армопоясу вручну', 'WORK', 'LINEAR_METER', 1800.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Бетонування армопоясу з міксера', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Установка закладних під комунікації', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Прокладка комунікацій', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Гідроізоляція плівкою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Гідроізоляція фундаменту мастикою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фундамент', 'Монтаж гвинтових паль', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Монтажні', 'Монтаж блоків ФБС', 'WORK', 'PIECE', 900.00, 1),
(gen_random_uuid(), 'BUILDER', 'Монтажні', 'Монтаж ж/б плит перекриття', 'WORK', 'PIECE', 1000.00, 1),
(gen_random_uuid(), 'BUILDER', 'Монтажні', 'Монтаж перемичок над прорізами', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Монтажні', 'Облаштування перемичок бетонних', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Гідроізоляція перед першим рядом', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка цегли 380 мм', 'WORK', 'M3', 4000.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка цегли 240 мм', 'WORK', 'M3', 4500.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка стін з газоблоку піноблоку 300 мм', 'WORK', 'M3', 2300.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка стін з газоблоку піноблоку 200 мм', 'WORK', 'M3', 3000.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка стіни з керамоблока 38х60х20', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка стіни з керамоблока 2НФ 25х12', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка облицювальної цегли', 'WORK', 'M2', 1900.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка стін з шлакоблоку', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка перегородки з піноблоку газоблоку до 50м2', 'WORK', 'M2', 600.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка перегородки з піноблоку газоблоку від 50м2', 'WORK', 'M2', 370.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка перегородки з цегли до 50м2', 'WORK', 'M2', 900.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка перегородки з цегли від 50м2', 'WORK', 'M2', 650.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Анкерування однієї стіни до іншої', 'WORK', 'PIECE', 45.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Армування кладки сіткою арматурою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Облаштування дверної пройми', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Приготування розчину для кладки без щебня', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Приготування розчину з щебнем', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Кладка', 'Кладка вентканалів і димоходу', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж односкатного даху комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж двоскатного даху комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж чотирьохскатного даху комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Балки перекриття', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж утеплювача на перекриття до 100мм', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж утеплювача на перекриття більше 100мм', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж утеплювача на покрівлю до 100мм', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж утеплювача на покрівлю більше 100мм', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Гідробар''єр паробар''єр', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж маурлата', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Обробка антисептиком', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Укладання шиферу або ондуліна', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Укладання бітумної черепиці', 'WORK', 'M2', 460.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Укладання металочерепиці', 'WORK', 'M2', 330.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж фальцевої покрівлі', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Укладання профнастилу', 'WORK', 'M2', 350.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж ОСБ плити', 'WORK', 'M2', 240.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Гідроізоляція поліуретановою мастикою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Гідроізоляція покрівлі мастика і євроруберойд', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Укладання підкладкового килима', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Підшива даху сайдінгом профнастилом', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Підшива даху дерев''яною вагонкою', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж лобової вітрової конькової планки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж капельника', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж планок закінчення стикування', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Установка флюгера ковпака на димохід', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Облаштування покрівель наплавлення руберойду один шар', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Облаштування покрівель наплавлення руберойду два шари', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Облаштування водостічної воронки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Монтаж водостоків жолоб труба', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Утеплення фасада комплекс пінопласт сітка декор штукатурка', 'WORK', 'M2', 1000.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Утеплення фасада комплекс вата сітка декор штукатурка', 'WORK', 'M2', 1200.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Монтаж пінопласта клей дюбель', 'WORK', 'M2', 300.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Монтаж вати клей дюбель', 'WORK', 'M2', 500.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Армування фасаду сітка перетяжка', 'WORK', 'M2', 290.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Грунтовка поверхні кварцгрунтом', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Декоративна штукатурка фасаду короїд баранець', 'WORK', 'M2', 330.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Фарбування фасаду', 'WORK', 'M2', 220.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Розділення розмітка двох кольорів декор штукатурки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Утеплення укосів пінопластом', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Утеплення укосів ватою', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Армування укосів сітка перетяжка', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Монтаж стартової планки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Утеплення цоколя пінополістиролом', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Облицювання клінкерною плиткою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Облицювання фасаду натуральним штучним каменем', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Монтаж будівельного риштування', 'WORK', 'M2', 50.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Демонтаж будівельного риштування', 'WORK', 'M2', 50.00, 1),
(gen_random_uuid(), 'BUILDER', 'Фасад', 'Монтаж відливів на вікна', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Планування ущільнення віброплитою під плитку до 20см', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Укладання тротуарної плитки на гарцовку', 'WORK', 'M2', 500.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Укладання бруківки старе місто на гарцовку', 'WORK', 'M2', 550.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Укладання армованої сітки для тротуарної плитки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Підрізка примикань тротуарної плитки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Приготування бетону для тротуарної плитки', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Приготування гарцовки для тротуарної плитки', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Облаштування жолоба для зливу води в плитці', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Доріжки з бетону з армуванням', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Доріжки з бетону без армування', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Монтаж бордюру для тротуарної плитки', 'WORK', 'LINEAR_METER', 280.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Монтаж бордюру дорожній', 'WORK', 'LINEAR_METER', 450.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Установка тротуарного бордюру коло радіус', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Установка останнього ряду плитки на розчин', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Установка піскоприймача в плитку', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Монтаж відливу водовідведення в плитку', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Благоустрій', 'Монтаж люка в тротуарну плитку', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан з дерева ранчо до 1.6м від 50мп', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан з дерева ранчо до 1.6м до 50мп', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан з профнастилу до 1.6м від 50мп', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан з профнастилу до 1.6м до 50мп', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан з штахет ламель до 1.6м від 50мп', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан з штахет ламель до 1.6м до 50мп', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан габіон до 1.6м', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Паркан габіон', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Установка дерев''яного металевого стовпа паркану', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Цоколь паркану бетонний 20х50', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Фундамент під цоколь паркану з шлакоблоків', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Кладка стовпів паркану під розшивку', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж шлакоблоків для стовбчика', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж шлакоблоків для цоколя паркана', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж кришки з бетону на цоколь паркана', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж кришки з бетону на стовбчик паркана', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж кришки з металу на стовбчик паркану', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж профнастилу на паркан до 2м', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж штахет ламель', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж композитної дошки на паркан', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Монтаж кришки з жерсті на низ паркану', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Паркан', 'Механізоване нанесення камінцевої штукатурки', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Зварювання каркасу сходів пряма сходинка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Зварювання каркасу сходів поворотна сходинка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Зварювання площадки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Бетонні сходи пряма сходинка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Бетонні сходи поворотна сходинка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Бетонна площадка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Бетонні сходи пряма сходинка заливка вручну', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Бетонні сходи поворотна сходинка заливка вручну', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Сходи', 'Бетонна площадка заливка вручну', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Зварювання', 'Зварювання рами розсувних воріт комплекс', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Зварювання', 'Зварювання рами розсувних воріт понад 7м комплекс', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Зварювання', 'Зварювання рами розпашних воріт комплекс', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Зварювання', 'Зварювання рами хвіртки комплекс', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Зварювання', 'Встановлення замка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Зварювання', 'Виготовлення ручки на хвіртку', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Хоз блок сарайчик комплекс робіт', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Виготовлення терас веранд комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Монтаж терасної дошки', 'WORK', 'M2', 650.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Фарбування терасної дошки', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Навіс легкий комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Навіс середній комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Навіс максимальний комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Споруди', 'Будівництво гаража комплекс', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Котел', 'Монтаж електричного котла', 'WORK', 'PIECE', 4500.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Заземлення', 'Електромонтаж контура заземлення', 'WORK', 'SET', 8000.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підготовка', 'Прокладка закладної гофри для резервного живлення', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підготовка', 'Перевірка цілісності кола продзвонка', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підготовка', 'Установка тимчасового освітлення розеток на час ремонту', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Вирізка ніші під електрощит 12-36 модулів', 'WORK', 'PIECE', 900.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Вирізка ніші під електрощит 48-60 модулів', 'WORK', 'PIECE', 1600.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Монтаж електрощита в нішу', 'WORK', 'PIECE', 900.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Монтаж електрощита накладного 12-36 модулів', 'WORK', 'PIECE', 800.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Монтаж електрощита накладного 48-60 модулів', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Монтаж електрощита накладного 72-90 модулів', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Монтаж електрощита накладного 120-180 модулів', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка контактора 220В', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка контактора 380В', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Нульові шини', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Встановлення розподільчого блоку на дин-рейку', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата однополюсного', 'WORK', 'PIECE', 220.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата двополюсного', 'WORK', 'PIECE', 440.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата трьохполюсного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата чотирьохполюсного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата перекидного двополюсного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата перекидного чотирьохполюсного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка реле перекидного чотирьохполюсного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка ПЗВ двополюсний', 'WORK', 'PIECE', 500.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка ПЗВ чотирьохполюсний', 'WORK', 'PIECE', 900.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка АВР', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка рубильника реверсивного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка автомата диференційного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка реле напруги однофазне', 'WORK', 'PIECE', 520.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка реле напруги трифазне', 'WORK', 'PIECE', 1500.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Щит', 'Установка крос-модуля', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель в гіпсокартоні', 'WORK', 'LINEAR_METER', 84.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель 20х20 в цеглі', 'WORK', 'LINEAR_METER', 140.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель 20х40 в цеглі', 'WORK', 'LINEAR_METER', 140.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель 20х60 в цеглі', 'WORK', 'LINEAR_METER', 160.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель 20х20 в бетоні', 'WORK', 'LINEAR_METER', 200.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель 40х20 в бетоні', 'WORK', 'LINEAR_METER', 220.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під електрокабель 60х20 в бетоні', 'WORK', 'LINEAR_METER', 250.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Штроблення під кабель канал', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Монтаж кабель каналу', 'WORK', 'LINEAR_METER', 400.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Прокладка кабелю', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Прокладка ретро проводу лофт відкрита', 'WORK', 'LINEAR_METER', 120.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Прокладка кабелю в гофрі', 'WORK', 'LINEAR_METER', 65.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Прокладка кабелю в металорукаві', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Прокладка силового кабелю', 'WORK', 'LINEAR_METER', 90.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Прокладка силового кабелю в гофрі трубі', 'WORK', 'LINEAR_METER', 90.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Опресовка наконечників кабельних', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Пайка кабелю', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Заробка штроб', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Отвір для підрозетника в гіпсокартоні', 'WORK', 'PIECE', 90.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Отвір для підрозетника в цеглі', 'WORK', 'PIECE', 140.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Отвір для підрозетника в бетоні', 'WORK', 'PIECE', 220.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Монтаж підрозетника', 'WORK', 'PIECE', 60.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Отвір для розподільчої коробки в гіпсокартоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Отвір для розподільчої коробки в цеглі', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Отвір для розподільчої коробки в бетоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Монтаж розподільчої коробки в стіну', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Монтаж розподільчої коробки на стелю', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Збірка розподільчої коробки розпаювання проводів', 'WORK', 'PIECE', 380.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Підрозетники', 'Комутація в підрозетнику', 'WORK', 'PIECE', 400.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Монтаж люка-ревізії під ТВ інтернет', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Монтаж вилки кабельної', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Установка промислової розетки на фасаді', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Установка та підключення розеток та вимикачів', 'WORK', 'PIECE', 140.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Установка прохідних перехресних вимикачів', 'WORK', 'PIECE', 300.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Установка накладних розетки вимикача коробки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Установка розетки для ТВ розгалуджувача', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки', 'Установка розетки комп''ютерної', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Свердління', 'Свердління наскрізних отворів у гіпсокартоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Свердління', 'Свердління наскрізних отворів у цеглі', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Свердління', 'Свердління наскрізних отворів у бетоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Свердління', 'Свердління отвору під кабель в капітальній стіні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Свердління', 'Свердління під точковий світильник в гіпсокартоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Свердління', 'Свердління під точковий світильник в рейковій стелі', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка та підключення точкового світильника софіта', 'WORK', 'PIECE', 250.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка та підключення трансформатора', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка та підключення стабілізатора напруги', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Монтаж світлодіодної стрічки в профілі', 'WORK', 'LINEAR_METER', 350.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Спайка світлодіодної стрічки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Складання люстри простої', 'WORK', 'PIECE', 800.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка підвісного світильника люстри простої', 'WORK', 'PIECE', 700.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка настінного світильника бра', 'WORK', 'PIECE', 350.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка світлодіодного світильника', 'WORK', 'PIECE', 350.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Монтаж шинопровода трекової системи', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Освітлення', 'Установка трекового світильника', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Прокладка закладної гофри в штробі для теплої підлоги', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Укладка підлоги електричної до 10м2', 'WORK', 'M2', 600.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Укладка підлоги електричної від 10м2', 'WORK', 'M2', 450.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Фіксація нагрівального мата спеціальним клеєм', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Укладка підлоги електричної інфрачервона плівкова', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Установка терморегулятора теплої підлоги', 'WORK', 'PIECE', 600.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Інше', 'Установка дверного дзвінка дротового', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Інше', 'Установка дверного дзвінка бездротового', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Інше', 'Установка кнопки дверного дзвінка', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Інше', 'Установка та підключення електроплити варочної', 'WORK', 'PIECE', 1200.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Інше', 'Установка та підключення відеодомофона', 'WORK', 'PIECE', 1500.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Інше', 'Установка датчиків руху датчиків світла', 'WORK', 'PIECE', 500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Обв''язка котла один котел 4 точки', 'WORK', 'POINT', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Монтаж котельної котел бойлер насоси крани фільтра', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка настінного двоконтурного котла', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка настінного одноконтурного котла з бойлером', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка твердопаливного котла', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Монтаж гідрострілки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Монтаж насосної групи', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Запуск системи опалення', 'WORK', 'PIECE', 1800.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Перевірка системи опалення тиском', 'WORK', 'PIECE', 1800.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Монтаж трубної системи тепла підлога з утеплювачем', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Виготовлення ніші під шафу колектора в цеглі', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Виготовлення ніші під шафу колектора в бетоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Монтаж колектора гребінки', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка та підключення унібокса', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка радіатора опалення простого', 'WORK', 'PIECE', 750.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка радіатора вертикального чавунного', 'WORK', 'PIECE', 1000.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка ніжок під радіатор з нижнім підключенням', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Установка терморегулятора на радіатор', 'WORK', 'PIECE', 250.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Обв''язка радіатора один радіатор 2 точки', 'WORK', 'POINT', 750.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Нарізання різьби на стояку опалення', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Штроблення в цеглі газобетоні (опалення)', 'WORK', 'LINEAR_METER', 250.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Штроблення в бетоні (опалення)', 'WORK', 'LINEAR_METER', 370.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Прокладання труб з ізоляцією (опалення)', 'WORK', 'LINEAR_METER', 100.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Прокладання труб на хомутах (опалення)', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Заробка штроб (опалення)', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Запуск системи водопроводу', 'WORK', 'PIECE', 1800.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Перевірка системи водопроводу тиском', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Виводи по точках з кінцевим елементом', 'WORK', 'POINT', 750.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж фільтра очищення води легка система', 'WORK', 'POINT', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж фільтра самопромивного', 'WORK', 'POINT', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж редуктора тиску води', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж гідрокомпенсатора', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Установка манометра', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Установка лічильника води простої складності', 'WORK', 'PIECE', 1000.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Установка лічильника води підвищеної складності', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Установка зворотного осмосу', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж системи від протікання води', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Врізка в стояк водопроводу', 'WORK', 'PIECE', 1500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж обладнання свердловини комплекс', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Монтаж насоса свердловини труби трос оголовок', 'WORK', 'SET', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Прокладання труб з ізоляцією (вода)', 'WORK', 'LINEAR_METER', 100.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Прокладання труб на хомутах (вода)', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Прокладка труб в траншеї', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Штроблення в цеглі газобетоні (вода)', 'WORK', 'LINEAR_METER', 250.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Водопостачання', 'Штроблення в бетоні (вода)', 'WORK', 'LINEAR_METER', 370.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Штроблення в газобетоні цеглі (каналізація)', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Штроблення в бетоні (каналізація)', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Штроблення під трубу 100мм в газобетоні цеглі', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Штроблення під трубу 100мм в бетоні', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Прокладка труб каналізації', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Прокладання труб на хомутах (каналізація)', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Розводка труб точка', 'WORK', 'POINT', 750.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Шумоізоляція стояка каналізації', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж заміна стояка пластик на пластик одна панель', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж заміна стояка пластик на пластик дві панелі', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж заміна стояка чавун на пластик одна панель', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж заміна стояка чавун на пластик дві панелі', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж зворотного клапана каналізації Ф50', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж зворотного клапана каналізації Ф110', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Установка компенсатора каналізаційного', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Монтаж сололіфта', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Каналізація', 'Врізка в стояк каналізації', 'WORK', 'PIECE', 1500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка ванни простої', 'WORK', 'PIECE', 2800.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка ванни асиметричної', 'WORK', 'PIECE', 3700.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка ванни з гідромасажем', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж скляних шторок на ванну', 'WORK', 'PIECE', 2000.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Шумоізоляція ванни', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Герметизація ванни силіконом', 'WORK', 'LINEAR_METER', 175.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка декоративного екрану під ванну', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка скляних розсувних дверей', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка душової кабіни простої', 'WORK', 'PIECE', 3000.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка душової кабіни бокс', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж гігієнічного душу', 'WORK', 'PIECE', 1600.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж тропічного душу', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж зливного трапа для душу', 'WORK', 'PIECE', 1600.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка простого унітазу біде', 'WORK', 'PIECE', 1400.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж інсталяції для унітазу', 'WORK', 'PIECE', 2600.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка унітазу на готову інсталяцію', 'WORK', 'PIECE', 1300.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж панелі з клавішами змиву', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка кранів', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка змішувача простого', 'WORK', 'PIECE', 700.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка змішувача окремостоячого підлоговий', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка змішувача прихованого типу для душа', 'WORK', 'PIECE', 1500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка змішувача прихованого типу умивальник', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж душової системи прихованого типу Smart Box', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка штанги', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка люка-ревізії простого', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка умивальника', 'WORK', 'PIECE', 950.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка дзеркала простого', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка сифона', 'WORK', 'PIECE', 500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж металевого сифона', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка рушникосушки', 'WORK', 'PIECE', 1350.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка та підключення вентилятора', 'WORK', 'PIECE', 425.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка та підключення бойлера', 'WORK', 'PIECE', 2500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка бойлера непрямого нагріву', 'WORK', 'PIECE', 4000.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка пральної сушильної машини', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Підключення посудомийної машини', 'WORK', 'PIECE', 1000.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка душового піддону готового', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж витяжки', 'WORK', 'PIECE', 1500.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж вентиляції', 'WORK', 'LINEAR_METER', 700.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Монтаж вентиляційної решітки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Зняття і встановлення радіатора під час ремонту', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Установка дверного доводчика', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Грунтовка поверхонь проста', 'WORK', 'M2', 40.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Грунтовка поверхонь бетоноконтактом', 'WORK', 'M2', 100.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Гідроізоляція підлоги стін в санвузлі мастика', 'WORK', 'M2', 150.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Гідроізоляція плівкова', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Гідроізоляція сухою сумішшю', 'WORK', 'M2', 130.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Монтаж гідроізоляційної стрічки', 'WORK', 'LINEAR_METER', 100.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Поклейка клейкої стрічки в кути', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Різка', 'Чистовий різ одна сторона', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Різка', 'Порізка плитки під кутом 45 градусів', 'WORK', 'LINEAR_METER', 500.00, 1),
(gen_random_uuid(), 'TILING', 'Різка', 'Порізка великоформатного керамограніту 45 градусів', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Різка', 'Вирізка отворів в плитці', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки об''ємом менше 20м2', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки на слой більше 1см', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки керамічної', 'WORK', 'M2', 850.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки мілкоформатної', 'WORK', 'M2', 1250.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 600х600', 'WORK', 'M2', 850.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1200х200', 'WORK', 'M2', 850.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1200х200 ялинкою', 'WORK', 'M2', 850.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1200х600', 'WORK', 'M2', 950.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 800х800', 'WORK', 'M2', 950.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 900х900', 'WORK', 'M2', 1000.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1500х750', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1000х1000', 'WORK', 'M2', 1100.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1200х1200', 'WORK', 'M2', 1250.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1500х1500', 'WORK', 'M2', 1500.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1200х2500', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки 1200х3000', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки кабанчик', 'WORK', 'M2', 1300.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання клінкерної плитки', 'WORK', 'M2', 1200.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання декоративної плитки під цеглу камінь', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання мозаїки', 'WORK', 'M2', 2500.00, 1),
(gen_random_uuid(), 'TILING', 'Укладання', 'Укладання плитки по діагоналі надбавка', 'WORK', 'PERCENT', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Сходи', 'Укладка плитки на сходи прямі без кута 45', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Сходи', 'Укладка плитки на підступок прямі без кута 45', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Сходи', 'Укладка плитки на сходи поворотні без кута 45', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Сходи', 'Укладка плитки на підступок поворотні без кута 45', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Сходи', 'Укладка плиткового фризу простого', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Сходи', 'Укладка плінтуса із плитки без затирання', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Формування кута епоксидною затиркою', 'WORK', 'LINEAR_METER', 350.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Поклейка стрічки на шви', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів проста', 'WORK', 'M2', 150.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів проста сформовані кути', 'WORK', 'LINEAR_METER', 150.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів двокомпонентною затиркою', 'WORK', 'M2', 320.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів двокомпонентна сформовані кути', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів герметиком', 'WORK', 'LINEAR_METER', 250.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів у декоративній плитці мозаїці', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Затирка', 'Затирка швів сухою сумішшю', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення душового піддону комплекс', 'WORK', 'PIECE', 2500.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Піддон з плитки з бортиком комплекс', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Піддон з плитки в рівень з підлогою комплекс', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Укладка плитки на душовий піддон конверт', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Установка люка-ревізії на магнітах', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення та монтаж ревізійного люка з плитки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення поличок з плитки три сторони до 30см', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення поличок з плитки чотири сторони до 30см', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення поличок з плитки три сторони від 30см', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення поличок з плитки чотири сторони від 30см', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Монтаж поличок з плитки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення та монтаж вбудованої витяжки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення та монтаж кнопки інсталяції з плитки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення раковини одинарної', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення раковини подвійної', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Монтаж раковини з плитки', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Спецроботи', 'Виготовлення та монтаж кріплення для раковини', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Звукоізоляція', 'Звукоізоляція стін мінеральною ватою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Звукоізоляція', 'Безкаркасна звукоізоляція стін', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Звукоізоляція', 'Безкаркасна звукоізоляція стелі', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Звукоізоляція', 'Каркасна звукоізоляція ГКЛ два слоя стін', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Звукоізоляція', 'Каркасна звукоізоляція ГКЛ два слоя стелі', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Звукоізоляція', 'Герметизація швів стиків герметиком', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Грунтовка поверхонь перед штукатуркою армуванням', 'WORK', 'M2', 40.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Грунтовка поверхонь бетоноконтактом', 'WORK', 'M2', 100.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Армування сіткою', 'WORK', 'M2', 140.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін машинкою до 2см', 'WORK', 'M2', 270.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін машинкою понад 2см', 'WORK', 'M2', 300.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін ручна до 2см', 'WORK', 'M2', 330.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін ручна від 2см', 'WORK', 'M2', 380.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін ручна від 5см', 'WORK', 'M2', 450.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін до 2см об''ємом до 50м2', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка стін від 2см об''ємом до 50м2', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Виведення геометрії стін кути 90', 'WORK', 'LINEAR_METER', 350.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка укосів', 'WORK', 'LINEAR_METER', 350.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Штукатурка під стельовий профіль натяжна стеля', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Штукатурка', 'Шліфування стін після штукатурки не нами', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Декор', 'Декоративна штукатурка китайський шовк вельвет лава сахара', 'WORK', 'M2', 450.00, 1),
(gen_random_uuid(), 'PAINTER', 'Декор', 'Декоративна штукатурка гротто 1000 ліній', 'WORK', 'M2', 450.00, 1),
(gen_random_uuid(), 'PAINTER', 'Декор', 'Декоративна штукатурка травертин', 'WORK', 'M2', 550.00, 1),
(gen_random_uuid(), 'PAINTER', 'Декор', 'Декоративна штукатурка ефект бетону арт бетон', 'WORK', 'M2', 550.00, 1),
(gen_random_uuid(), 'PAINTER', 'Декор', 'Декоративна штукатурка мікробетон', 'WORK', 'M2', 700.00, 1),
(gen_random_uuid(), 'PAINTER', 'Декор', 'Декоративна штукатурка мармурова крихта ферозит', 'WORK', 'M2', 500.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Чищення бетонних плит підготовчі', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Заробка стиків у бетоні', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Заробка тріщин раковин шліфування', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Збирання сміття в мішки після демонтажу', 'WORK', 'PIECE', 15.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Захист підлоги картоном', 'WORK', 'M2', 30.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Захист вікна плівкою картоном', 'WORK', 'PIECE', 200.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Грунтовка поверхонь перед шпаклівкою фарбуванням', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Паробар''єр гідробар''єр', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Стелі Грильято', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Стеля Армстронг', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Оздоблення', 'Монтаж на стелю пластикової вагонки', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Монтаж дерев''яної вагонки на стіну', 'WORK', 'M2', 450.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Монтаж дерев''яної вагонки на стелю', 'WORK', 'M2', 550.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Фарбування дерев''яної вагонки', 'WORK', 'M2', 220.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Монтаж нашовної планки на стики вагонки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Фарбування нашовної планки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Обрешітка дерев''яною рейкою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Обшивка ОСП фанерою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Обшивка стелі шалівкою', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Укладання ламінату на стіну на обрешітку', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Вагонка', 'Поклейка ламінату на стіну', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Вирівнювання стін не нами за погодженням', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Дефектовка стін не нами за погодженням', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Ошкурення стін після шпаклівки не нами', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Виведення кутів без стельового багета шпаклівкою', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Виведення кутів пофарбуванням', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Поклейка сітки в кути', 'WORK', 'LINEAR_METER', 100.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Шпаклівка старт по цементній штукатурці', 'WORK', 'M2', 200.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Шпаклівка стін під склополотно шпалери', 'WORK', 'M2', 330.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Шпаклівка стелі під склополотно шпалери', 'WORK', 'M2', 360.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Шпаклівка стелі під фарбування', 'WORK', 'M2', 420.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Шпаклівка стін під фарбування', 'WORK', 'M2', 380.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпаклівка', 'Шпаклівка коробів укосів ніш під фарбування', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпалери', 'Поклейка склополотна', 'WORK', 'M2', 160.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпалери', 'Поклейка шпалер 100см без підбору', 'WORK', 'M2', 200.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпалери', 'Поклейка шпалер 100см з підбором', 'WORK', 'M2', 220.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпалери', 'Поклейка шпалер 50см без підбору', 'WORK', 'M2', 200.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпалери', 'Поклейка шпалер 50см з підбором', 'WORK', 'M2', 240.00, 1),
(gen_random_uuid(), 'PAINTER', 'Шпалери', 'Поклейка фотошпалер', 'WORK', 'M2', 450.00, 1),
(gen_random_uuid(), 'PAINTER', 'Фарбування', 'Фарбування грунт-фарбою', 'WORK', 'M2', 100.00, 1),
(gen_random_uuid(), 'PAINTER', 'Фарбування', 'Фарбування стін водоемульсійною фарбою', 'WORK', 'M2', 180.00, 1),
(gen_random_uuid(), 'PAINTER', 'Фарбування', 'Фарбування стелі водоемульсійною фарбою', 'WORK', 'M2', 220.00, 1),
(gen_random_uuid(), 'PAINTER', 'Багети', 'Установка перфорованих кутів на укоси', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Багети', 'Монтаж стельових багетів пінопласт до 8см', 'WORK', 'LINEAR_METER', 170.00, 1),
(gen_random_uuid(), 'PAINTER', 'Багети', 'Монтаж стельових багетів поліуретанових до 6см', 'WORK', 'LINEAR_METER', 220.00, 1),
(gen_random_uuid(), 'PAINTER', 'Багети', 'Фарбування стельових багетів пінопласт', 'WORK', 'LINEAR_METER', 100.00, 1),
(gen_random_uuid(), 'PAINTER', 'Багети', 'Фарбування стельових багетів поліуретанових', 'WORK', 'LINEAR_METER', 120.00, 1),
(gen_random_uuid(), 'PAINTER', 'Багети', 'Монтаж молдінга з поліуретану', 'WORK', 'LINEAR_METER', 270.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підвіконня', 'Вирівнювання пройми під підвіконня', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підвіконня', 'Чистка підготовка віконної пройми під підвіконня', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підвіконня', 'Установка підвіконня', 'WORK', 'LINEAR_METER', 750.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підвіконня', 'Заробка штроби під підвіконням', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підвіконня', 'Монтаж віконного профіля з гумою', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підвіконня', 'Герметизація швів стиків акрилом мастикою', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Двері', 'Фарбування дверей', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Двері', 'Опуск дверної пройми', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Двері', 'Установка люка з драбиною на горище', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Двері', 'Фарбування труб газової опалення', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'PAINTER', 'Двері', 'Монтаж 3Д панелей', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Підготовка', 'Монтаж на висоті більше 3м надбавка', 'WORK', 'PERCENT', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стелі', 'Монтаж короба прямого по периметру стелі', 'WORK', 'LINEAR_METER', 500.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стелі', 'Монтаж короба радіусного по периметру стелі', 'WORK', 'LINEAR_METER', 550.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стелі', 'Монтаж ніші під прихований карниз короб під комунікації', 'WORK', 'LINEAR_METER', 550.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стелі', 'Монтаж профілю тіньового шва по периметру стелі', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стелі', 'Монтаж гіпсокартону на стелю зі скосами', 'WORK', 'M2', 700.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стелі', 'Монтаж гіпсокартону на стелю рівну', 'WORK', 'M2', 560.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Стіни', 'Монтаж гіпсокартону на стіни', 'WORK', 'M2', 430.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Перегородки', 'Монтаж перегородки ГКЛ 2 сторони в 1 шар', 'WORK', 'M2', 650.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Перегородки', 'Монтаж перегородки ГКЛ 2 сторони в 2 шари', 'WORK', 'M2', 750.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Перегородки', 'Монтаж радіусної перегородки ГКЛ в 1 шар', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Перегородки', 'Монтаж радіусної перегородки ГКЛ в 2 шари', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Інше', 'Утеплення мінватою в один шар', 'WORK', 'M2', 160.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Інше', 'Монтаж укосів із гіпсокартону', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Інше', 'Вирізка отворів в гіпсокартоні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Інше', 'Заробка стиків у гіпсокартоні поклейка серпянки', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Інше', 'Обшивка інсталяції в т.ч. отвори', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Інше', 'Монтаж екрану ванни з підступком', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Кладка перегородки з піноблоку газоблоку до 50м2', 'WORK', 'M2', 600.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Кладка перегородки з піноблоку газоблоку від 50м2', 'WORK', 'M2', 370.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Кладка перегородки з цегли до 50м2', 'WORK', 'M2', 900.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Кладка перегородки з цегли від 50м2', 'WORK', 'M2', 650.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Анкерування однієї стіни до іншої', 'WORK', 'PIECE', 45.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Армування кладки сіткою арматурою', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Облаштування дверного пройому звуження розширення', 'WORK', 'PIECE', 800.00, 1),
(gen_random_uuid(), 'DRYWALL', 'Кладка', 'Кладка цегляної підстави під ванну', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Шліфування бетону стяжки', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Підготовка поверхні очищення', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Грунтовка під стяжку', 'WORK', 'M2', 40.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Плівкова ізоляція під стяжку', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Армування підлоги сіткою під стяжку', 'WORK', 'M2', 130.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Монтаж утеплювача під стяжку', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Монтаж демпферної стрічки', 'WORK', 'M2', 50.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Цементно-піщана стяжка до 20м2', 'WORK', 'M2', 500.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Цементно-піщана стяжка понад 20м2', 'WORK', 'M2', 400.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Вирівнювання підлоги самовирівнюючим розчином', 'WORK', 'M2', 300.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Штроблення в стяжці під монтаж перегородок', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Стяжка', 'Заливаня штроби в стяжці', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Чистка підлоги порохотягом підготовка', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Грунтовка підлоги підготовчі роботи', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Шліфування дерев''яної підлоги', 'WORK', 'M2', 250.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Настил лінолеуму ковроліну', 'WORK', 'M2', 200.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Настил лінолеуму ковроліну на клей', 'WORK', 'M2', 200.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Влаштування дерев''яних лаг', 'WORK', 'M2', 300.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Настил підлоги із дошки', 'WORK', 'M2', 400.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Укладка ламінату проста', 'WORK', 'M2', 300.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Укладка ламінату по діагоналі', 'WORK', 'M2', 350.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Укладка кварцвінілу на підкладку', 'WORK', 'M2', 350.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Укладка кварцвінілу на клей', 'WORK', 'M2', 420.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Підрізка ламінату защільнення', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Підлога', 'Монтаж терасної дошки', 'WORK', 'M2', 650.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж плінтуса пластик', 'WORK', 'LINEAR_METER', 150.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж пробкового компенсатора', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж плінтуса шпонованого МДФ', 'WORK', 'LINEAR_METER', 280.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж плінтуса алюмінієвого', 'WORK', 'LINEAR_METER', 400.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж плінтуса прихованого монтажу', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж та виготовлення ніші під плінтус прихованого', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж плінтуса дерев''яного', 'WORK', 'LINEAR_METER', 250.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж плінтуса з полістиролу', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Фарбування плінтуса', 'WORK', 'LINEAR_METER', 140.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Нанесення лаку тонера на підлогу', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Монтаж міжкімнатного порога', 'WORK', 'LINEAR_METER', 400.00, 1),
(gen_random_uuid(), 'FLOORING', 'Плінтус', 'Приклеювання стиків порожків герметизація', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Демонтаж цегляної стіни', 'WORK', 'M2', 100.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Демонтаж перегородки з цегли півцеглини', 'WORK', 'M2', 70.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Демонтаж перегородки з гіпсокартону', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Демонтаж перегородки з піноблоку газоблоку', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Вирізка прорізу в цегляній стіні', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Розширення дверного прорізу', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Збивання штукатурки зі стін', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Зняття шпалер', 'WORK', 'M2', 30.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стін', 'Зняття старої фарби зі стін', 'WORK', 'M2', 80.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж стяжки бетонної', 'WORK', 'M2', 65.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж керамічної плитки з підлоги', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж плитки зі стін', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж ламінату паркету', 'WORK', 'M2', 25.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж лінолеуму ковроліну', 'WORK', 'M2', 20.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж дерев''яної підлоги лаг', 'WORK', 'M2', 70.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж підлоги', 'Демонтаж плінтуса', 'WORK', 'LINEAR_METER', 30.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стелі', 'Демонтаж гіпсокартонної стелі', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стелі', 'Демонтаж натяжної стелі', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж стелі', 'Демонтаж стельового багета', 'WORK', 'LINEAR_METER', 30.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж сантехніки', 'Демонтаж ванни', 'WORK', 'PIECE', 600.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж сантехніки', 'Демонтаж унітазу', 'WORK', 'PIECE', 350.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж сантехніки', 'Демонтаж умивальника раковини', 'WORK', 'PIECE', 200.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж сантехніки', 'Демонтаж душової кабіни', 'WORK', 'PIECE', 500.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж сантехніки', 'Демонтаж радіатора опалення', 'WORK', 'PIECE', 350.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж сантехніки', 'Демонтаж старих труб', 'WORK', 'LINEAR_METER', 100.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж столярки', 'Демонтаж міжкімнатних дверей з коробкою', 'WORK', 'PIECE', 150.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж столярки', 'Демонтаж вхідних дверей', 'WORK', 'PIECE', 200.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж столярки', 'Демонтаж вікна балконного блоку', 'WORK', 'PIECE', 250.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж столярки', 'Демонтаж підвіконня', 'WORK', 'PIECE', 100.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж електрики', 'Демонтаж старої електропроводки', 'WORK', 'LINEAR_METER', 50.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж електрики', 'Демонтаж розеток вимикачів', 'WORK', 'PIECE', 60.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Демонтаж електрики', 'Демонтаж електрощита', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Сміття', 'Винесення будівельного сміття', 'WORK', 'M3', 200.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Сміття', 'Фасування сміття в мішки', 'WORK', 'PIECE', 15.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Сміття', 'Вантаження сміття в авто', 'WORK', 'M3', 0.00, 1),
(gen_random_uuid(), 'DEMOLITION', 'Сміття', 'Підйом будматеріалів на поверх', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Слаботочка', 'Прокладка інтернет-кабелю витої пари', 'WORK', 'LINEAR_METER', 65.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Слаботочка', 'Установка інтернет-розетки RJ45', 'WORK', 'PIECE', 250.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Слаботочка', 'Монтаж ТВ-кабелю', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Слаботочка', 'Установка слаботочного щита', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'ELECTRICAL', 'Слаботочка', 'Налаштування Wi-Fi роутера точки доступу', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'PLUMBING', 'Лічильники', 'Опломбування лічильника води', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'TILING', 'Підготовка', 'Демонтаж старої плитки перед укладанням', 'WORK', 'M2', 60.00, 1),
(gen_random_uuid(), 'PAINTER', 'Підготовка', 'Розшивка та заробка тріщин', 'WORK', 'LINEAR_METER', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Розчищення території від чагарників', 'WORK', 'M2', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Спил дерева', 'WORK', 'PIECE', 0.00, 1),
(gen_random_uuid(), 'BUILDER', 'Земляні', 'Викорчовування пнів', 'WORK', 'PIECE', 0.00, 1);

-- 5. Existing users stay at version 0 (the column default) — their catalog was
--    seeded from the OLD thin starter templates, so the new by-trade default set
--    (v1) IS new to them. "Add new from catalog" therefore offers them the full
--    default catalog for their trades, de-duplicated against what they already
--    own (never overwrites prices). New users from here on are synced to the
--    current version on register/reset (CatalogTemplateService), so for them the
--    button shows nothing until a future v2+ ships. No UPDATE needed here.
