-- V35 — default MATERIAL positions per trade (~295). The default catalog was
-- 100% WORK (a labour reference); this adds the common materials a master lists in a
-- client estimate — with orientative market prices (rabotniki/Epicentr-grounded; some
-- are market estimates the master corrects, same as V31 prices). type='MATERIAL',
-- added_in_version=3 so existing masters get them via "Add new from library" and fresh
-- registrations get them seeded. Trades already use the DB enum codes.
INSERT INTO catalog_templates (id, trade, category, name, type, unit, suggested_price, added_in_version) VALUES
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ВВГ 3х1.5', 'MATERIAL', 'M', 38.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ВВГ 3х2.5', 'MATERIAL', 'M', 59.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ВВГ 3х4', 'MATERIAL', 'M', 94.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ВВГ 3х6', 'MATERIAL', 'M', 140.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ВВГ 3х10', 'MATERIAL', 'M', 235.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ВВГ 5х6', 'MATERIAL', 'M', 320.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Провід ПВ-3 (ПУГВ) 1х2.5 заземлення', 'MATERIAL', 'M', 20.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель ПВС 3х2.5', 'MATERIAL', 'M', 60.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель UTP cat5e інтернет', 'MATERIAL', 'M', 12.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Кабель', 'Кабель коаксіальний ТВ RG-6', 'MATERIAL', 'M', 15.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Розетка з заземленням прихована', 'MATERIAL', 'PIECE', 120.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Розетка подвійна з заземленням', 'MATERIAL', 'PIECE', 230.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Розетка вологозахищена IP44', 'MATERIAL', 'PIECE', 150.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Розетка з USB-зарядкою', 'MATERIAL', 'PIECE', 380.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Вимикач одноклавішний', 'MATERIAL', 'PIECE', 110.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Вимикач двоклавішний', 'MATERIAL', 'PIECE', 160.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Вимикач прохідний одноклавішний', 'MATERIAL', 'PIECE', 200.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Диммер світлорегулятор', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Датчик руху для освітлення', 'MATERIAL', 'PIECE', 300.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Рамка суппорт для розеток', 'MATERIAL', 'PIECE', 45.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Автоматичний вимикач 1п 16А тип C', 'MATERIAL', 'PIECE', 180.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Автоматичний вимикач 1п 25А', 'MATERIAL', 'PIECE', 190.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Автоматичний вимикач 2п 40А ввідний', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'ПЗВ 2п 40А 30мА', 'MATERIAL', 'PIECE', 1100.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Диференційний автомат 1п+N 16А 30мА', 'MATERIAL', 'PIECE', 600.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Електрощит вбудований на 12 модулів', 'MATERIAL', 'PIECE', 700.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Бокс зовнішній навісний IP65 8-12 мод', 'MATERIAL', 'PIECE', 550.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'DIN-рейка 35мм 0.5м', 'MATERIAL', 'PIECE', 40.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Щит і автоматика', 'Стабілізатор напруги побутовий', 'MATERIAL', 'PIECE', 3500.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Підрозетник для бетону/цегли', 'MATERIAL', 'PIECE', 10.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Розподільча коробка прихована', 'MATERIAL', 'PIECE', 25.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Гофра ПВХ 16мм з протяжкою', 'MATERIAL', 'M', 9.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Кабель-канал 25х16мм', 'MATERIAL', 'M', 25.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Клеми Wago 222 на 3 контакти', 'MATERIAL', 'PIECE', 15.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Клеми Wago 221 компактні', 'MATERIAL', 'PIECE', 18.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Клеми Wago 773 без важеля', 'MATERIAL', 'PIECE', 8.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Наконечник-гільза НШВІ', 'MATERIAL', 'PIECE', 2.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Стяжки кабельні нейлонові 100 шт', 'MATERIAL', 'SET', 40.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Дюбель-хомут для кабелю 100 шт', 'MATERIAL', 'SET', 40.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Монтажне', 'Ізоляційна стрічка ПВХ 20м', 'MATERIAL', 'PIECE', 25.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Терморегулятор теплої підлоги', 'MATERIAL', 'PIECE', 900.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Тепла підлога', 'Нагрівальний мат теплої підлоги', 'MATERIAL', 'M2', 900.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Розетки і вимикачі', 'Дзвінок дверний провідний', 'MATERIAL', 'PIECE', 250.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Світильники', 'Точковий світильник врізний LED GU10', 'MATERIAL', 'PIECE', 130.00, 3),
(gen_random_uuid(), 'ELECTRICAL', 'Світильники', 'Світильник стельовий LED накладний', 'MATERIAL', 'PIECE', 600.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба інтер''єрна водоемульсійна', 'MATERIAL', 'PIECE', 750.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба інтер''єрна акрилова', 'MATERIAL', 'PIECE', 850.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба інтер''єрна латексна миюча', 'MATERIAL', 'PIECE', 1100.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба інтер''єрна силіконова', 'MATERIAL', 'PIECE', 1400.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба для стель матова', 'MATERIAL', 'PIECE', 550.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба інтер''єрна напівматова', 'MATERIAL', 'PIECE', 900.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Фарба фасадна акрилова', 'MATERIAL', 'PIECE', 1300.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Грунт-фарба пігментована підкладкова', 'MATERIAL', 'PIECE', 700.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Емаль алкідна ПФ-115', 'MATERIAL', 'KG', 130.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Лак акриловий для дерева/стін', 'MATERIAL', 'PIECE', 500.00, 3),
(gen_random_uuid(), 'PAINTER', 'Фарби', 'Антисептик-просочення для дерева', 'MATERIAL', 'PIECE', 400.00, 3),
(gen_random_uuid(), 'PAINTER', 'Грунтовки', 'Грунтовка глибокого проникнення', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'PAINTER', 'Грунтовки', 'Грунтовка глибокопроникна концентрат', 'MATERIAL', 'PIECE', 250.00, 3),
(gen_random_uuid(), 'PAINTER', 'Грунтовки', 'Грунтовка бетоноконтакт адгезійна', 'MATERIAL', 'PIECE', 1100.00, 3),
(gen_random_uuid(), 'PAINTER', 'Грунтовки', 'Грунтовка бетоноконтакт 4.5 кг', 'MATERIAL', 'PIECE', 500.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Шпаклівка стартова гіпсова', 'MATERIAL', 'PIECE', 280.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Шпаклівка фінішна гіпсова', 'MATERIAL', 'PIECE', 375.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Шпаклівка фінішна полімерна готова', 'MATERIAL', 'PIECE', 600.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Шпаклівка фасадна', 'MATERIAL', 'PIECE', 320.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Шпаклівка Фугенфюллер для швів ГК', 'MATERIAL', 'PIECE', 485.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Штукатурка гіпсова Rotband', 'MATERIAL', 'PIECE', 490.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Штукатурка гіпсова стартова HP Start', 'MATERIAL', 'PIECE', 330.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Штукатурка цементна фасадна', 'MATERIAL', 'PIECE', 220.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Штукатурка машинного нанесення MP', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Декоративна штукатурка короїд 25 кг', 'MATERIAL', 'PIECE', 700.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Декоративна штукатурка мозаїчна', 'MATERIAL', 'PIECE', 1200.00, 3),
(gen_random_uuid(), 'PAINTER', 'Шпаклівки і штукатурки', 'Декоративна штукатурка венеційська', 'MATERIAL', 'KG', 150.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Стрічка малярна паперова 48 мм', 'MATERIAL', 'PIECE', 35.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Стрічка паперова широка для швів', 'MATERIAL', 'PIECE', 60.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Серп''янка самоклеюча 45 мм', 'MATERIAL', 'PIECE', 70.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Склосітка армуюча малярна 5х5', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Сітка для шпаклівки склосітка дрібна', 'MATERIAL', 'M2', 15.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Склополотно павутинка під фарбування', 'MATERIAL', 'M2', 25.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Куточок штукатурний перфорований 3 м', 'MATERIAL', 'PIECE', 45.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Кутник арочний перфорований 2.5 м', 'MATERIAL', 'PIECE', 60.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Плівка захисна малярна укривна', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Валик малярний велюровий у зборі', 'MATERIAL', 'PIECE', 150.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Валик поролоновий', 'MATERIAL', 'PIECE', 70.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Валик ниткова шуба', 'MATERIAL', 'PIECE', 130.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Ванночка малярна кюветка', 'MATERIAL', 'PIECE', 60.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Набір шпателів', 'MATERIAL', 'SET', 250.00, 3),
(gen_random_uuid(), 'PAINTER', 'Допоміжне', 'Пензель малярний', 'MATERIAL', 'PIECE', 60.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Прибирання сміття', 'Мішки для будівельного сміття 55х105 см (100 шт)', 'MATERIAL', 'SET', 1187.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Прибирання сміття', 'Мішки для сміття посилені (10 шт)', 'MATERIAL', 'SET', 90.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Прибирання сміття', 'Біг-бег МКР на 1 т', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Захист поверхонь', 'Плівка захисна поліетиленова 1.5х50 м рулон', 'MATERIAL', 'PIECE', 300.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Захист поверхонь', 'Стрейч-плівка 500 мм рулон', 'MATERIAL', 'PIECE', 180.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Захист поверхонь', 'Скотч малярний 50 мм х 27 м', 'MATERIAL', 'PIECE', 40.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Захист поверхонь', 'Скотч армований 48 мм х 50 м', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Захист поверхонь', 'Картон захисний для підлоги рулон', 'MATERIAL', 'PIECE', 400.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Витратні', 'Диск відрізний по металу 125 мм', 'MATERIAL', 'PIECE', 30.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Витратні', 'Диск відрізний по металу 230 мм', 'MATERIAL', 'PIECE', 55.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Витратні', 'Диск алмазний по бетону 230 мм', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'Витратні', 'Полотно для шабельної пилки набір', 'MATERIAL', 'SET', 150.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'ЗІЗ', 'Рукавиці робочі з ПВХ 10 пар', 'MATERIAL', 'SET', 260.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'ЗІЗ', 'Респіратор протипиловий FFP2', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'DEMOLITION', 'ЗІЗ', 'Окуляри захисні будівельні', 'MATERIAL', 'PIECE', 55.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба поліпропіленова армована Ø20 PN20', 'MATERIAL', 'M', 42.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба поліпропіленова армована Ø25 PN20', 'MATERIAL', 'M', 60.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба поліпропіленова армована Ø32 PN20', 'MATERIAL', 'M', 100.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба металопластикова Ø16', 'MATERIAL', 'M', 30.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба металопластикова Ø20', 'MATERIAL', 'M', 45.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба каналізаційна ПВХ Ø50', 'MATERIAL', 'M', 45.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Труби', 'Труба каналізаційна ПВХ Ø110', 'MATERIAL', 'M', 90.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Фітинги', 'Коліно поліпропіленове Ø25 90°', 'MATERIAL', 'PIECE', 12.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Фітинги', 'Трійник поліпропіленовий Ø25', 'MATERIAL', 'PIECE', 18.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Фітинги', 'Муфта з''єднувальна поліпропіленова Ø25', 'MATERIAL', 'PIECE', 12.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Фітинги', 'Американка поліпропіленова Ø25х3/4', 'MATERIAL', 'PIECE', 75.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Фітинги', 'Муфта перехідна поліпропіленова Ø32/25', 'MATERIAL', 'PIECE', 20.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Фітинги', 'Коліно каналізаційне ПВХ Ø110 90°', 'MATERIAL', 'PIECE', 45.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Запірна арматура', 'Кран кульовий 1/2 вода', 'MATERIAL', 'PIECE', 120.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Запірна арматура', 'Кран кульовий 3/4 вода', 'MATERIAL', 'PIECE', 160.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Запірна арматура', 'Вентиль кран-букса 1/2', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Змішувачі', 'Змішувач для раковини стандарт', 'MATERIAL', 'PIECE', 900.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Змішувачі', 'Змішувач для ванни з душем', 'MATERIAL', 'PIECE', 1400.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Змішувачі', 'Змішувач для душу', 'MATERIAL', 'PIECE', 1100.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Змішувачі', 'Змішувач прихованого монтажу комплект', 'MATERIAL', 'SET', 4200.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Унітаз-компакт санфаянс', 'MATERIAL', 'SET', 3500.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Унітаз підвісний чаша', 'MATERIAL', 'PIECE', 3200.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Інсталяція для унітаза з бачком', 'MATERIAL', 'SET', 4500.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Раковина накладна умивальник', 'MATERIAL', 'PIECE', 1800.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Ванна акрилова 150х70', 'MATERIAL', 'PIECE', 6500.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Ванна сталева 150х70', 'MATERIAL', 'PIECE', 5000.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Сантехприлади', 'Душовий піддон акриловий 90х90', 'MATERIAL', 'PIECE', 3000.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Сифон для раковини', 'MATERIAL', 'PIECE', 150.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Сифон для душового піддона', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Трап для душу нерж 10х10', 'MATERIAL', 'PIECE', 550.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Гнучка підводка 1/2 60 см', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Фум-стрічка', 'MATERIAL', 'PIECE', 25.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Лляна нитка сантехнічна', 'MATERIAL', 'PIECE', 80.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Захист водопроводу', 'Редуктор тиску води 1/2', 'MATERIAL', 'PIECE', 550.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Захист водопроводу', 'Фільтр грубої очистки 1/2', 'MATERIAL', 'PIECE', 180.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Захист водопроводу', 'Лічильник води крильчастий ХВ', 'MATERIAL', 'PIECE', 450.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Радіатор біметалевий секція 500мм', 'MATERIAL', 'PIECE', 380.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Радіатор алюмінієвий секція 500мм', 'MATERIAL', 'PIECE', 320.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Кран Маєвського 1/2', 'MATERIAL', 'PIECE', 40.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Кріплення хомут для труб Ø25', 'MATERIAL', 'PIECE', 8.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Допоміжне', 'Утеплювач для труб Ø22', 'MATERIAL', 'M', 25.00, 3),
(gen_random_uuid(), 'PLUMBING', 'Опалення', 'Бойлер водонагрівач 80 л', 'MATERIAL', 'PIECE', 5500.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Ламінат 32 клас побутовий', 'MATERIAL', 'M2', 300.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Ламінат 33 клас комерційний', 'MATERIAL', 'M2', 550.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Ламінат 33 клас водостійкий', 'MATERIAL', 'M2', 850.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Кварцвініл SPC ламінат', 'MATERIAL', 'M2', 780.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Вініловий ламінат LVT клейовий', 'MATERIAL', 'M2', 650.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Лінолеум побутовий', 'MATERIAL', 'M2', 350.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Лінолеум напівкомерційний', 'MATERIAL', 'M2', 500.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Паркетна дошка дуб 3-шарова', 'MATERIAL', 'M2', 1650.00, 3),
(gen_random_uuid(), 'FLOORING', 'Покриття', 'Інженерна дошка дуб', 'MATERIAL', 'M2', 1800.00, 3),
(gen_random_uuid(), 'FLOORING', 'Підкладка', 'Підкладка спінений поліетилен 3 мм', 'MATERIAL', 'M2', 30.00, 3),
(gen_random_uuid(), 'FLOORING', 'Підкладка', 'Підкладка XPS 3 мм листова', 'MATERIAL', 'M2', 55.00, 3),
(gen_random_uuid(), 'FLOORING', 'Підкладка', 'Підкладка пробкова 2 мм', 'MATERIAL', 'M2', 130.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Плінтус пластиковий ПВХ 2.5 м', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Плінтус МДФ 2.4 м', 'MATERIAL', 'PIECE', 230.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Плінтус дерев''яний дуб 2.5 м', 'MATERIAL', 'PIECE', 320.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Кут для плінтуса', 'MATERIAL', 'PIECE', 15.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'З''єднувач для плінтуса', 'MATERIAL', 'PIECE', 12.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Заглушка для плінтуса пара', 'MATERIAL', 'SET', 18.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Поріг алюмінієвий стик', 'MATERIAL', 'PIECE', 220.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Клей для паркету дисперсійний 25 кг', 'MATERIAL', 'PIECE', 1400.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Клей для лінолеуму/ПВХ 14 кг', 'MATERIAL', 'PIECE', 1585.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Клей-герметик швів для ламінату', 'MATERIAL', 'PIECE', 250.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Стяжка цементна для підлоги 25 кг', 'MATERIAL', 'PIECE', 165.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Ровнітель грубий стартовий 25 кг', 'MATERIAL', 'PIECE', 200.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Наливна підлога самовирівнювальна 25 кг', 'MATERIAL', 'PIECE', 240.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Демпферна стрічка 100 мм х 50 м', 'MATERIAL', 'PIECE', 180.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Демпферна стрічка з плівкою 150 мм х 50 м', 'MATERIAL', 'PIECE', 380.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Плівка гідроізоляційна 200 мкм рулон', 'MATERIAL', 'PIECE', 900.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Сітка армувальна для стяжки', 'MATERIAL', 'M2', 40.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Лак паркетний поліуретановий 1 л', 'MATERIAL', 'PIECE', 550.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Олія-віск для паркету 1 л', 'MATERIAL', 'PIECE', 750.00, 3),
(gen_random_uuid(), 'FLOORING', 'Захист', 'Віск для деревини 0.5 л', 'MATERIAL', 'PIECE', 300.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Набір монтажний для укладання ламінату', 'MATERIAL', 'SET', 250.00, 3),
(gen_random_uuid(), 'FLOORING', 'Клеї та суміші', 'Клини монтажні розпірні набір', 'MATERIAL', 'SET', 90.00, 3),
(gen_random_uuid(), 'FLOORING', 'Плінтус і пороги', 'Поріг ламінований стик МДФ', 'MATERIAL', 'PIECE', 160.00, 3),
(gen_random_uuid(), 'BUILDER', 'Стіни і кладка', 'Газоблок 300х200х600 D500', 'MATERIAL', 'PIECE', 45.00, 3),
(gen_random_uuid(), 'BUILDER', 'Стіни і кладка', 'Газоблок 400х200х600 D500', 'MATERIAL', 'PIECE', 60.00, 3),
(gen_random_uuid(), 'BUILDER', 'Стіни і кладка', 'Цегла червона рядова М100', 'MATERIAL', 'PIECE', 8.00, 3),
(gen_random_uuid(), 'BUILDER', 'Стіни і кладка', 'Цегла силікатна одинарна', 'MATERIAL', 'PIECE', 6.00, 3),
(gen_random_uuid(), 'BUILDER', 'Стіни і кладка', 'Цегла облицювальна червона', 'MATERIAL', 'PIECE', 22.00, 3),
(gen_random_uuid(), 'BUILDER', 'Цемент і суміші', 'Цемент М400 ПЦ ІІ 25 кг', 'MATERIAL', 'PIECE', 130.00, 3),
(gen_random_uuid(), 'BUILDER', 'Цемент і суміші', 'Цемент М500 ПЦ І 25 кг', 'MATERIAL', 'PIECE', 155.00, 3),
(gen_random_uuid(), 'BUILDER', 'Цемент і суміші', 'Клей для газоблоку 25 кг', 'MATERIAL', 'PIECE', 145.00, 3),
(gen_random_uuid(), 'BUILDER', 'Заповнювачі', 'Пісок будівельний кар''єрний', 'MATERIAL', 'T', 550.00, 3),
(gen_random_uuid(), 'BUILDER', 'Заповнювачі', 'Пісок будівельний', 'MATERIAL', 'M3', 750.00, 3),
(gen_random_uuid(), 'BUILDER', 'Заповнювачі', 'Щебінь гранітний фракція 5-20', 'MATERIAL', 'T', 850.00, 3),
(gen_random_uuid(), 'BUILDER', 'Заповнювачі', 'Щебінь гранітний фракція 5-20', 'MATERIAL', 'M3', 1250.00, 3),
(gen_random_uuid(), 'BUILDER', 'Цемент і суміші', 'Бетон товарний М200 з доставкою', 'MATERIAL', 'M3', 3550.00, 3),
(gen_random_uuid(), 'BUILDER', 'Цемент і суміші', 'Бетон товарний М300 з доставкою', 'MATERIAL', 'M3', 3900.00, 3),
(gen_random_uuid(), 'BUILDER', 'Метал/армування', 'Арматура А500С Ø8', 'MATERIAL', 'M', 18.00, 3),
(gen_random_uuid(), 'BUILDER', 'Метал/армування', 'Арматура А500С Ø10', 'MATERIAL', 'M', 22.00, 3),
(gen_random_uuid(), 'BUILDER', 'Метал/армування', 'Арматура А500С Ø12', 'MATERIAL', 'M', 27.00, 3),
(gen_random_uuid(), 'BUILDER', 'Метал/армування', 'Сітка кладкова зварна 50х50 Ø3-4', 'MATERIAL', 'M2', 95.00, 3),
(gen_random_uuid(), 'BUILDER', 'Метал/армування', 'Сітка зварна 100х100 Ø4 карта', 'MATERIAL', 'M2', 130.00, 3),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Профнастил стіновий С10 кольоровий', 'MATERIAL', 'M2', 210.00, 3),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Профнастил покрівельний ПК-20', 'MATERIAL', 'M2', 250.00, 3),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Металочерепиця глянець', 'MATERIAL', 'M2', 250.00, 3),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Гнучка бітумна черепиця', 'MATERIAL', 'M2', 320.00, 3),
(gen_random_uuid(), 'BUILDER', 'Утеплення', 'Пінопласт фасадний EPS-100 50 мм', 'MATERIAL', 'M2', 130.00, 3),
(gen_random_uuid(), 'BUILDER', 'Утеплення', 'Пінопласт фасадний EPS-100 100 мм', 'MATERIAL', 'M2', 250.00, 3),
(gen_random_uuid(), 'BUILDER', 'Утеплення', 'Мінеральна базальтова вата 100 мм', 'MATERIAL', 'M2', 180.00, 3),
(gen_random_uuid(), 'BUILDER', 'Утеплення', 'ЕППС пеноплекс 50 мм', 'MATERIAL', 'M2', 175.00, 3),
(gen_random_uuid(), 'BUILDER', 'Пиломатеріали', 'OSB-3 вологостійка 9 мм лист', 'MATERIAL', 'PIECE', 380.00, 3),
(gen_random_uuid(), 'BUILDER', 'Пиломатеріали', 'OSB-3 вологостійка 12 мм лист', 'MATERIAL', 'PIECE', 490.00, 3),
(gen_random_uuid(), 'BUILDER', 'Пиломатеріали', 'Дошка обрізна суха сосна', 'MATERIAL', 'M3', 9500.00, 3),
(gen_random_uuid(), 'BUILDER', 'Пиломатеріали', 'Брус будівельний сосна 100х100', 'MATERIAL', 'M3', 8500.00, 3),
(gen_random_uuid(), 'BUILDER', 'Ізоляція', 'Гідробар''єр покрівельна плівка рулон 75 м2', 'MATERIAL', 'PIECE', 850.00, 3),
(gen_random_uuid(), 'BUILDER', 'Ізоляція', 'Пароізоляція плівка рулон 75 м2', 'MATERIAL', 'PIECE', 700.00, 3),
(gen_random_uuid(), 'BUILDER', 'Утеплення', 'Фасадна склосітка 5х5 рулон 50 м2', 'MATERIAL', 'PIECE', 950.00, 3),
(gen_random_uuid(), 'BUILDER', 'Утеплення', 'Фасадна склосітка', 'MATERIAL', 'M2', 22.00, 3),
(gen_random_uuid(), 'BUILDER', 'Цемент і суміші', 'Клей для пінопласту 25 кг', 'MATERIAL', 'PIECE', 220.00, 3),
(gen_random_uuid(), 'BUILDER', 'Кріплення', 'Дюбель-парасоля для утеплювача 10х140', 'MATERIAL', 'PIECE', 4.00, 3),
(gen_random_uuid(), 'BUILDER', 'Фарби і грунтовки', 'Грунтовка фасадна 10 л', 'MATERIAL', 'PIECE', 320.00, 3),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Водостічний жолоб металевий', 'MATERIAL', 'LINEAR_METER', 85.00, 3),
(gen_random_uuid(), 'BUILDER', 'Покрівля', 'Водостічна труба ПВХ', 'MATERIAL', 'LINEAR_METER', 70.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Листи', 'Гіпсокартон стіновий 12.5 мм 2500х1200', 'MATERIAL', 'PIECE', 300.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Листи', 'Гіпсокартон вологостійкий 12.5 мм', 'MATERIAL', 'PIECE', 370.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Листи', 'Гіпсокартон стельовий 9.5 мм', 'MATERIAL', 'PIECE', 260.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Листи', 'Гіпсокартон стельовий вологостійкий 9.5 мм', 'MATERIAL', 'PIECE', 340.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Листи', 'Гіпсокартон вогнестійкий 12.5 мм', 'MATERIAL', 'PIECE', 430.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Листи', 'ГВЛ гіпсоволокнистий лист 10 мм', 'MATERIAL', 'PIECE', 720.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Профіль стельовий CD 60х27 3 м', 'MATERIAL', 'PIECE', 150.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Профіль напрямний UD 28х27 3 м', 'MATERIAL', 'PIECE', 110.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Профіль стійковий CW 50 3 м', 'MATERIAL', 'PIECE', 200.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Профіль напрямний UW 50 3 м', 'MATERIAL', 'PIECE', 190.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Профіль стійковий CW 75 3 м', 'MATERIAL', 'PIECE', 260.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Профіль стійковий CW 100 3 м', 'MATERIAL', 'PIECE', 310.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Профіль', 'Кутовий маячковий профіль 3 м', 'MATERIAL', 'PIECE', 60.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Підвіс прямий П-подібний для CD 60', 'MATERIAL', 'PIECE', 6.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Подовжувач профілю CD 60', 'MATERIAL', 'PIECE', 6.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Краб з''єднувач однорівневий CD 60', 'MATERIAL', 'PIECE', 12.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Анкерний підвіс з тягою CD 60', 'MATERIAL', 'PIECE', 18.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Саморізи по металу LN 3.5х9.5 1000 шт', 'MATERIAL', 'SET', 260.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Саморізи по ГКЛ 3.5х25 1000 шт', 'MATERIAL', 'SET', 320.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Саморізи по ГКЛ 3.5х35 1000 шт', 'MATERIAL', 'SET', 420.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Дюбель швидкого монтажу 6х40 100 шт', 'MATERIAL', 'SET', 70.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Дюбель для ГКЛ метелик 10х60 100 шт', 'MATERIAL', 'SET', 130.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Кріплення', 'Дюбель для ГКЛ Molly металевий', 'MATERIAL', 'PIECE', 7.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Стрічка-серпянка армуюча 45 мм х 90 м', 'MATERIAL', 'PIECE', 80.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Стрічка паперова для швів 50 мм х 150 м', 'MATERIAL', 'PIECE', 400.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Кутник перфорований металевий 3 м', 'MATERIAL', 'PIECE', 70.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Кутник перфорований пластиковий 3 м', 'MATERIAL', 'PIECE', 16.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Кутник арочний гнучкий пластиковий 3 м', 'MATERIAL', 'PIECE', 18.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Грунтовка глибокого проникнення 10 л', 'MATERIAL', 'PIECE', 340.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Шпаклівка для швів Фугенфюллер 25 кг', 'MATERIAL', 'PIECE', 500.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Шви і суміші', 'Фінішна шпаклівка полімерна 20 кг', 'MATERIAL', 'PIECE', 560.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Ізоляція', 'Мінеральна вата в перегородку 50 мм', 'MATERIAL', 'M2', 110.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Ізоляція', 'Мінеральна вата в перегородку 100 мм', 'MATERIAL', 'M2', 200.00, 3),
(gen_random_uuid(), 'DRYWALL', 'Ізоляція', 'Ущільнювальна стрічка під профіль 30 мм х 30 м', 'MATERIAL', 'PIECE', 180.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Плитка керамічна для стін', 'MATERIAL', 'M2', 450.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Плитка для підлоги', 'MATERIAL', 'M2', 550.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Керамограніт', 'MATERIAL', 'M2', 750.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Керамограніт великоформатний', 'MATERIAL', 'M2', 1300.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Плитка під дерево', 'MATERIAL', 'M2', 700.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Плитка під мармур', 'MATERIAL', 'M2', 850.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Клінкерна плитка фасадна', 'MATERIAL', 'M2', 750.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Мозаїка скляна/керамічна', 'MATERIAL', 'M2', 1400.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Плитка-сходинка з капіносом', 'MATERIAL', 'PIECE', 550.00, 3),
(gen_random_uuid(), 'TILING', 'Плитка', 'Плінтус/бордюр для плитки', 'MATERIAL', 'PIECE', 180.00, 3),
(gen_random_uuid(), 'TILING', 'Клеї та суміші', 'Клей для плитки стандартний 25 кг', 'MATERIAL', 'PIECE', 322.00, 3),
(gen_random_uuid(), 'TILING', 'Клеї та суміші', 'Клей для плитки посилений еластичний 25 кг', 'MATERIAL', 'PIECE', 850.00, 3),
(gen_random_uuid(), 'TILING', 'Клеї та суміші', 'Клей для керамограніту 25 кг', 'MATERIAL', 'PIECE', 480.00, 3),
(gen_random_uuid(), 'TILING', 'Клеї та суміші', 'Клей для плитки білий 25 кг', 'MATERIAL', 'PIECE', 700.00, 3),
(gen_random_uuid(), 'TILING', 'Клеї та суміші', 'Клей для теплої підлоги 25 кг', 'MATERIAL', 'PIECE', 420.00, 3),
(gen_random_uuid(), 'TILING', 'Клеї та суміші', 'Клей швидкотвердіючий 25 кг', 'MATERIAL', 'PIECE', 450.00, 3),
(gen_random_uuid(), 'TILING', 'Грунтовки', 'Грунтовка бетоноконтакт 15 кг', 'MATERIAL', 'PIECE', 1450.00, 3),
(gen_random_uuid(), 'TILING', 'Грунтовки', 'Грунтовка глибокого проникнення 10 л', 'MATERIAL', 'PIECE', 645.00, 3),
(gen_random_uuid(), 'TILING', 'Грунтовки', 'Праймер під гідроізоляцію', 'MATERIAL', 'PIECE', 700.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Затирка для швів цементна 2 кг', 'MATERIAL', 'PIECE', 200.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Затирка для швів еластична 2 кг', 'MATERIAL', 'PIECE', 407.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Затирка біла 2 кг', 'MATERIAL', 'PIECE', 190.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Затирка кольорова 2 кг', 'MATERIAL', 'PIECE', 230.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Затирка для широкого шва', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Затирка епоксидна 2.5 кг', 'MATERIAL', 'PIECE', 2400.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Герметик силіконовий санітарний', 'MATERIAL', 'PIECE', 250.00, 3),
(gen_random_uuid(), 'TILING', 'Затирки', 'Клей-герметик MS-полімер', 'MATERIAL', 'PIECE', 300.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Хрестики для плитки 200 шт', 'MATERIAL', 'SET', 50.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Система вирівнювання плитки СВП комплект', 'MATERIAL', 'SET', 354.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Затискачі СВП 100 шт', 'MATERIAL', 'SET', 120.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Клини СВП 100 шт', 'MATERIAL', 'SET', 110.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Диск/ролик для плиткоріза', 'MATERIAL', 'PIECE', 490.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Шпатель зубчастий 8 мм', 'MATERIAL', 'PIECE', 160.00, 3),
(gen_random_uuid(), 'TILING', 'Гідроізоляція', 'Гідроізоляція обмазувальна 25 кг', 'MATERIAL', 'PIECE', 630.00, 3),
(gen_random_uuid(), 'TILING', 'Гідроізоляція', 'Гідроізоляція двокомпонентна еластична', 'MATERIAL', 'PIECE', 1900.00, 3),
(gen_random_uuid(), 'TILING', 'Гідроізоляція', 'Гідроізоляційна стрічка рулон 10 м', 'MATERIAL', 'PIECE', 1350.00, 3),
(gen_random_uuid(), 'TILING', 'Гідроізоляція', 'Гідроізоляційна стрічка за м', 'MATERIAL', 'M', 90.00, 3),
(gen_random_uuid(), 'TILING', 'Гідроізоляція', 'Гідроізоляційна манжета для кутів/труб', 'MATERIAL', 'PIECE', 220.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Профіль/куточок для плитки алюмінієвий 2.5 м', 'MATERIAL', 'PIECE', 220.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Профіль для плитки пластиковий 2.5 м', 'MATERIAL', 'PIECE', 90.00, 3),
(gen_random_uuid(), 'TILING', 'Допоміжне', 'Профіль для сходинок алюмінієвий', 'MATERIAL', 'PIECE', 350.00, 3),
(gen_random_uuid(), 'TILING', 'Гідроізоляція', 'Мат теплої підлоги під плитку', 'MATERIAL', 'M2', 1000.00, 3);
