-- Annual PRO tariff (229 ₴/mo paid once for 12 months = 2748 ₴).
--
-- payments.period carries the tariff a payment bought, and its CHECK constraint
-- enumerates the allowed values — so a YEAR checkout would fail at INSERT until the
-- constraint is widened. (users.renew_period has no CHECK, so auto-renew needs nothing.)
--
-- V41 created that CHECK inline on ADD COLUMN, so its name was generated by Postgres.
-- Dropping a guessed name would silently no-op and leave the old constraint rejecting
-- YEAR at runtime — so every CHECK on payments mentioning `period` is dropped by lookup.

DO $$
DECLARE
    c record;
BEGIN
    FOR c IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        WHERE rel.relname = 'payments'
          AND nsp.nspname = current_schema()
          AND con.contype = 'c'
          AND pg_get_constraintdef(con.oid) ILIKE '%period%'
    LOOP
        EXECUTE format('ALTER TABLE payments DROP CONSTRAINT %I', c.conname);
    END LOOP;
END $$;

ALTER TABLE payments ADD CONSTRAINT payments_period_check
    CHECK (period IN ('MONTH', 'HALF_YEAR', 'YEAR'));
